In [2]:
import numpy as np

In [3]:
# Declaration of 1-D numpy array
a = np.array([32,61,72])

In [4]:
print(a,a[1])

[32 61 72] 61


In [5]:
np.dot?

Call signature:  np.dot(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function dot>
Docstring:      
dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to
  :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
  preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS library when possible (see `numpy.linalg`).

Parameters
----------
a : array_like
    Fi

In [6]:
b = np.array([82,23,12])

In [7]:
np.dot(a,b) #multiplies two arrays

np.int64(4891)

In [8]:
p=(a*b).sum() # tell sum of array
print(p)
print(type(p))

4891
<class 'numpy.int64'>


In [9]:
a.sum()

np.int64(165)

In [10]:
print(a.sum())

165


Why Numpy arrays are better than python list

**Ease of Use** -> numpy arrays opertaions are small, concise and intuitive mathematical expressions

**Performance** -> numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements and loops which are interpreted at runtime

In [11]:
%%time 
# %%time -> specific jupyter notebook feature, tells time taken to run that cell
np.dot(a,b)

CPU times: user 76 μs, sys: 9 μs, total: 85 μs
Wall time: 104 μs


np.int64(4891)

In [37]:
# 2D array
climate_data = np.array([[73, 67, 43],
                         [91, 8, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [38]:
# 2D array (matrix)
# We can inspect the length along each dimension using the .shape property of an array.
# it gives a tuple
climate_data.shape 

(5, 3)

In [47]:
# dtype -> tells data type
climate_data.dtype

dtype('int64')

All the elements in numpy array has same datatype. if even a single integer is coverted to float then all will be converted into float or string.

<U21 means: A Unicode string array where each element can hold up to 21 characters.

In [41]:
weight = np.array([0.3, 0.2, 0.5])

In [44]:
# matmul -> function for matrix multiplication in numpy
np.matmul(climate_data,weight)

array([56.8, 60.9, 81.9, 57.7, 74.9])

In [45]:
climate_data @ weight # another method for matrix multiplication in numpy

array([56.8, 60.9, 81.9, 57.7, 74.9])