In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1qVONanAmp0Rpn_GDiZa9BsMyZXKEq9vB')

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Numpy


### What is numpy?

NumPy is a module for Python, which stands for "Numerical Python" or "Numeric Python". The main purpose of this module is for numeric computation in Python. It has tools and techniques designed to solve numerical problems in Python. The Numpy array data structure, for example, is one of the tools that makes working with numeric data in Python very efficient. There are a number of functions that can be found in the Numpy module. This extension module for Python, mostly written in C. This makes sure that the precompiled mathematical and numerical functions and functionalities of Numpy guarantee great execution speed. Below are five of them to be discussed in this notebook, wich is very used in Data Science: 

- function 1 - argmax()
- function 2 - count_nonzero()
- function 3 - append()
- function 4 - insert()
- function 5 - isnan()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [ ]:
!pip install jovian --upgrade -q

In [ ]:
import jovian

In [28]:
jovian.commit(project='numpy-array-operations', privacy='secret', evironment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/numpy-array-operations


'https://jovian.ml/masedos/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.argmax
function2 = np.count_nonzero
function3 = np.append
function4 = np.insert
function5 = np.isnan

## Function 1 - np.argmax()

numpy.argmax(a, axis=None, out=None) <br>
With this function you can returns the indices of the maximum values along an axis. Or you can say return the position of the largest value

No argmax returns the position of the largest value. max returns the largest value.

In [ ]:
# Example 1 - Working

x = np.array([[10, 11, 12], 
              [13, 14, 15], 
              [16, 17, 18]]) # 3D array
np.argmax(x)

8

Here we found the max position of the value in the array.

In [ ]:
# Example 2 - Working
x = np.array([[19, 11, 12], 
              [13, 44, 15], 
              [16, 17, 18]]) # 3D array
np.argmax(x, axis=0)

array([0, 1, 2])

The indices of max element on the axis zero

In [3]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([4, 5, 6, 7])
np.argmax(x, axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

Here we looking for the max value in the axis 1, but there is just axis 0

This function is excellente when you have a n dimensional matrix, and wanted to know the max value in that matrix.

In [29]:
jovian.commit(project='numpy-array-operations', privacy='secret', evironment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/numpy-array-operations


'https://jovian.ml/masedos/numpy-array-operations'

## Function 2 - np.count_nonzero()

numpy.count_nonzero(a, axis=None, *, keepdims=False)<br>
Counts the number of non-zero values in the array a. It takes an array as an argument and returns the number of non-zero values in the array. It takes two other optional arguments which are the axis along which to count the non-zero values and the 'keep dimension' option which can be set to True or False

In [ ]:
# Example 1 - working
x = np.array([[1,  66, 0,  44 ],
              [11, 0,  30, 0],
              [0,  1,  7,  33]])
np.count_nonzero(x, axis=None)

8

count the quantity of number that is not a zero in the array

In [ ]:
# Example 2 - working
x = np.array([[10, 40, 0, 60],
              [0,  10, 0, 0]])                           
np.count_nonzero(x, axis=0)

array([1, 2, 0, 1])

unt the quantity of number that is not a zero in the array by the axis 0

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([[3, 5, 6,],
              [2, 6, 0],
              [3, 0]])
np.count_nonzero(x, axis=1)

AxisError: ignored

all the element in the axis 1 need to be in the same dimensaional size, the solve the problem you need to use axis 0 or format the array to be the same size.

Excellent to know how many zero there is in the array.

In [30]:
jovian.commit(project='numpy-array-operations', privacy='secret', evironment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/numpy-array-operations


'https://jovian.ml/masedos/numpy-array-operations'

## Function 3 - np.append()

numpy.append(arr, values, axis=None)<br>
Append values to the end of an array. It is used to combine two or more arrays into a single array

In [ ]:
# Example 1 - working
x = np.arange(5)
y = np.arange(6, 11)

np.append(y, x, axis=None)

array([ 6,  7,  8,  9, 10,  0,  1,  2,  3,  4])

Combine two array with one dimensional each in single array

In [ ]:
# Example 2 - working
x = np.array([[2, 6, 8],
              [5, 7, 5]])

y = np.array([[3, 1, 4],
              [7, 8, 11]])

np.append(x, y, axis=0)

array([[ 2,  6,  8],
       [ 5,  7,  5],
       [ 3,  1,  4],
       [ 7,  8, 11]])

Combine two array ( 2 x 3 ) in a array (4 x 3)

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([12.4, 6, 11.8, 13.1, 14, 15.3]).reshape(2, 3)

np.append(x, [9.6, 8.9, 10.3], axis=0)

ValueError: ignored

all the input arrays must have same number of dimensions

 It can be used to combine different dataset into one dataset for analysis to be done on it

In [31]:
jovian.commit(project='numpy-array-operations', privacy='secret', evironment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/numpy-array-operations


'https://jovian.ml/masedos/numpy-array-operations'

## Function 4 - np. insert()

numpy.insert(arr, obj, values, axis=None)<br>
Insert values along the given axis before the given indices.

In [ ]:
# Example 1 - working
x = np.array([[4, 6, 11], [8, 7, 5]])

np.insert(x, 1, [9, 13, 15])

array([ 4,  9, 13, 15,  6, 11,  8,  7,  5])

The values was inseted exactly axis in the array

In [ ]:
# Example 2 - working
x = np.array([[4, 6, 11], [8, 7, 5]])

np.insert(x, 1, [9, 13, 15], axis=0)

array([[ 4,  6, 11],
       [ 9, 13, 15],
       [ 8,  7,  5]])

In this case the values was inserted at the row index of 1

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([[4, 6, 11], [8, 7, 5]])

np.insert(x, 1, [9, 13], axis=0)

ValueError: ignored

In this case the values cant be inserted in a diffente shape of array on the axis 1, they need to be in the same shape.

Excellente to insert value in the array, to change the shape of.

In [32]:
jovian.commit(project='numpy-array-operations', privacy='secret', evironment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/numpy-array-operations


'https://jovian.ml/masedos/numpy-array-operations'

## Function 5 - np.isnan()

numpy.isnan(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'isnan'> <br>
Test element-wise for NaN and return result as a boolean array. This function is perfect to know if there is NaN in the dataset.

In [ ]:
# Example 1 - working
x = np.array([[1, -5, 7], [0, 4, 11], [9, 10, 6], [3, 7, 6]])

np.isnan(x)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

Show if in the array exist any NaN value

In [ ]:
# Example 2 - working
x = np.array([[1, -5, 7], [0, 4, 11], [9, 10, 6], [3, 7, 6.]])

x[0,2] = np.nan
x[3, 1] = np.nan
x

array([[ 1., -5., nan],
       [ 0.,  4., 11.],
       [ 9., 10.,  6.],
       [ 3., nan,  6.]])

Do way you can see some value NaN was add in the array

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
np.isnan(np.array([[np.nan, 8],
                   [6, 11]], 
                  dtype=object))

TypeError: ignored

A NaN values can't be inseted in the type of the object.

One of the most function used in the data analysis to find NaN value.

In [33]:
jovian.commit(project='numpy-array-operations', privacy='secret', evironment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/numpy-array-operations


'https://jovian.ml/masedos/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [34]:
jovian.commit(project='numpy-array-operations', privacy='secret', evironment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/numpy-array-operations


'https://jovian.ml/masedos/numpy-array-operations'