# Numpy

### What is numpy?

NumPy is a module for Python, which stands for "Numerical Python" or "Numeric Python". The main purpose of this module is for numeric computation in Python. It has tools and techniques designed to solve numerical problems in Python. The Numpy array data structure, for example, is one of the tools that makes working with numeric data in Python very efficient. There are a number of functions that can be found in the Numpy module. This extension module for Python, mostly written in C. This makes sure that the precompiled mathematical and numerical functions and functionalities of Numpy guarantee great execution speed.

In [2]:
import numpy as np

In [3]:
# Declaration of 1-D numpy array
a = np.array([32,61,72])

In [4]:
print(a,a[1])

[32 61 72] 61


In [5]:
np.dot?

Call signature:  np.dot(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function dot>
Docstring:      
dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to
  :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
  preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS library when possible (see `numpy.linalg`).

Parameters
----------
a : array_like
    Fi

In [6]:
b = np.array([82,23,12])

In [7]:
np.dot(a,b) #multiplies two arrays

np.int64(4891)

In [8]:
p=(a*b).sum() # tells sum of array
print(p)
print(type(p))

4891
<class 'numpy.int64'>


In [9]:
a.sum()

np.int64(165)

In [10]:
print(a.sum())

165


Why Numpy arrays are better than python list

**Ease of Use** -> numpy arrays opertaions are small, concise and intuitive mathematical expressions

**Performance** -> numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements and loops which are interpreted at runtime

In [11]:
%%time 
# %%time -> specific jupyter notebook feature, tells time taken to run that cell
np.dot(a,b)

CPU times: user 54 μs, sys: 1 μs, total: 55 μs
Wall time: 59.8 μs


np.int64(4891)

In [12]:
# 2D array
climate_data = np.array([[73, 67, 43],
                         [91, 8, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [13]:
# 2D array (matrix)
# We can inspect the length along each dimension using the .shape property of an array.
# it gives a tuple
climate_data.shape 

(5, 3)

In [14]:
# dtype -> tells data type
climate_data.dtype

dtype('int64')

In [9]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [12]:
arr3.shape

(2, 2, 3)

for 3D only -> In above shape last 2 and 3 tells one matrix size and first 2 tells how many mantrices are there. 

All the elements in numpy array has same datatype. if even a single integer is coverted to float then all will be converted into float or string.

<U21 means: A Unicode string array where each element can hold up to 21 characters.

In [15]:
weight = np.array([0.3, 0.2, 0.5])

In [16]:
# matmul -> function for matrix multiplication in numpy
np.matmul(climate_data,weight)

array([56.8, 60.9, 81.9, 57.7, 74.9])

In [17]:
climate_data @ weight # another method for matrix multiplication in numpy

array([56.8, 60.9, 81.9, 57.7, 74.9])

# Working with CSV data files

```
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')
```

#### Theory
**urllib** -> urllib is a standard Python module for working with URLs (Uniform Resource Locators).
 It allows you to:

    * Open URLs like you open files (urlopen)
    * Download files (urlretrieve)
    * Encode/decode URLs
    * Work with HTTP headers and requests

 urllib.request.urlretrieve(url, filename)

    * Downloads a file from a url and saves it as filename.
    * It returns a tuple: (filename, headers) (though you didn’t store that in your code).
    * Under the hood, it opens the URL, reads the contents, and writes it to a file.

```climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)```

**genfromtxt** -> np.genfromtxt() is a NumPy function used to load data from a text file, especially when the data is in CSV or similar format. It’s more flexible than np.loadtxt() because it can handle missing values, skip headers, etc.

`'climate.txt'
→ The name of the file to read. This should be your previously downloaded file.

delimiter=','
→ The file uses commas to separate values (i.e., it's a CSV format).
If you skip this, it assumes whitespace as the separator.

skip_header=1
→ Skips the first line of the file, which usually contains column names like "Temperature, Rainfall, Humidity".`

#### every data inside the climate.txt is now stored in climate_data, now we can use **climate_data @ weigths** to get the value for whole data

In [18]:
# yield = climate_data @ weights
# yield
# yield.shape -> (10000,)

We can now add the `yields` back to `climate_data` as a fourth column using the [`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function.

```climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)```

This line combines two NumPy arrays horizontally, adding the yields column as a new feature to the climate_data.
✅ Step-by-Step Breakdown

1. **np.concatenate(...)**

    This function joins two or more arrays along a specified axis.

2. **(climate_data, yields.reshape(10000, 1))**

    A tuple containing the arrays to be joined.

    `climate_data:` A 2D array of shape (10000, N)
    (e.g., N features like temperature, rainfall, etc.)

    `yields:` A 1D array of shape (10000,)
    (e.g., one yield value per data point)

    `.reshape(10000, 1)`: Reshapes yields into a column vector of shape (10000, 1)
    ➤ This is required because you cannot concatenate a 1D array with a 2D array along axis 1.

3. **axis=1**

    This tells NumPy to concatenate along columns (i.e., horizontally).
    ➤ It adds the yields column as a new feature (the last column) in the dataset.

In [17]:
np.argmax?

Signature:       np.argmax(a, axis=None, out=None, *, keepdims=<no value>)
Call signature:  np.argmax(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function argmax at 0x7fafe1baf0a0>
File:            ~/.local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Returns the indices of the maximum values along an axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    By default, the index is into the flattened array, otherwise
    along the specified axis.
out : array, optional
    If provided, the result will be inserted into this array. It should
    be of the appropriate shape and dtype.
keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the array.

    .. versionadded:: 1.22.0

Returns
-------
index_array : ndarray of ints
    Array of indices into the a

In [18]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...),
    axis=0,
    out=None,
    dtype=None,
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'

In [19]:
np.reshape?

Signature:       np.reshape(a, /, shape=None, order='C', *, newshape=None, copy=None)
Call signature:  np.reshape(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function reshape at 0x7fafe1bae440>
File:            ~/.local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
shape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of ``a`` using this index order, and place the
    elements into the reshaped array using this index order. 'C'
    means to read / write the elements using C-like index order,
    with the last axis ind

```
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')
```

The results are written back in the CSV format to the file `climate_results.txt`. If file is already present then it will overwrite the file.  

```
temperature,rainfall,humidity,yeild_apples
25.00 76.00 99.00 72.20
39.00 65.00 70.00 59.70
59.00 45.00 77.00 65.20
84.00 63.00 38.00 56.80
66.00 50.00 52.00 55.80
41.00 94.00 77.00 69.60
91.00 57.00 96.00 86.70
49.00 96.00 99.00 83.40
67.00 20.00 28.00 38.10
...
```

✅ Function Purpose

**np.savetxt(...)** is a NumPy function used to save a NumPy array to a text file, with control over formatting, header, delimiter, and more.
📌 Parameter-by-Parameter Explanation
1. `'climate_results.txt'`

    This is the filename (a string).

    It tells NumPy where to save the text file.

    If a file with this name already exists, it will be overwritten without warning.

2. `climate_results`

    This is the NumPy array you are saving to the file.

    Must be a 2D array (e.g., shape (10000, 4)) — each row will be written as one line in the file.

3. `fmt='%.2f'`

    fmt stands for format — it defines how each number should be written in the file.

    '%.2f' means:

        %.2f = floating point number with 2 digits after the decimal point

        For example, 3.14159 → 3.14

    This applies to every value in the array.

4. `header='temperature,rainfall,humidity,yeild_apples'`

    This is a string that will be written as the first line in the file.

    Acts like column headers (good for readability or importing into spreadsheets).

    It appears above the data in the file.

    Example:

    temperature,rainfall,humidity,yeild_apples
    22.56,300.12,85.43,15.77
    ...

5. `comments=''`

    By default, np.savetxt adds a # before the header, because headers are treated as comments.

    Setting comments='' removes that symbol, so the header is written without a #.

Numpy provides hundreds of functions for peforming operations on arrays. Here are some common functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How to find the function you need?** Since Numpy offers hundreds of functions for operating on arrays, it can sometimes be hard to find exactly what you need. The easiest way to find the right function is to do a web search e.g. searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

## Arithmetic operations and broadcasting

In [20]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [21]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [22]:
# Adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [23]:
# Element-wise subtraction
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

Numpy arrays also support *brodcasting*, which allows arthmetic operations between two array having a different number of dimensions

In [24]:
arr2.shape

(3, 4)

In [25]:
arr4 = np.array([4, 5, 6, 7])

In [26]:
arr4.shape

(4,)

In [27]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape `(4,)`) is replicated 3 times to match the shape `(3, 4)` of `arr2`. This is pretty useful, because numpy performs the replication without actually creating 3 copies of the smaller dimension array.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the other array.

## Array Indexing and Slicing

In [29]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [30]:
arr3.shape

(3, 2, 4)

In [34]:
arr3[2, 0, 3] # Single element

np.float64(23.0)

In [33]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [35]:
arr3[1:, 1, 3]

array([18., 43.])

In [36]:
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [37]:
# Using fewer indices
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

## Other ways of creating Numpy arrays

Numpy also provides some handy functions to create arrays of a desired shape with fixed or random values. Check the out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more about the following functions.

In [38]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# Random vector
np.random.rand(5)

array([0.30448846, 0.21015539, 0.27289544, 0.24405304, 0.91244849])

In [42]:
# Random matrix
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[ 0.064647  , -2.01479819,  0.02359419],
       [-1.28688339, -0.80893504, -0.64747425]])

**rand vs randn**

Use rand when you want uniformly distributed values between 0 and 1. Generates random floats in the range [0, 1).
Uniform distribution: every number in the range has equal probability.

Use randn when you need values that follow a Gaussian/normal distribution, centered at 0. Generates random numbers from the standard normal distribution:

    Mean = 0

    Std deviation = 1

    Bell-shaped curve

In [44]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [45]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [46]:
# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

- (Optional) 100 numpy exercises: https://github.com/rougier/numpy-100

Check out the following resouces for learning more about Numpy:

- Official tutorial: https://numpy.org/devdocs/user/quickstart.html
- Numpy tutorial on W3Schools: https://www.w3schools.com/python/numpy_intro.asp
- Advanced Numpy (exploring the internals): http://scipy-lectures.org/advanced/advanced_numpy/index.html